export const FETCH_USER = "FETCH_USER";
export const LOGUED_USER_WITH_MAIL_AND_PASSWORD_SUCCES =
  "LOGUED_USER_WITH_MAIL_AND_PASSWORD_SUCCES";
export const LOGUED_USER_WITH_MAIL_AND_PASSWORD_LOADING =
  "LOGUED_USER_WITH_MAIL_AND_PASSWORD_LOADING";
export const LOGUED_USER_WITH_MAIL_AND_PASSWORD_ERROR =
  "LOGUED_USER_WITH_MAIL_AND_PASSWORD_ERROR";
export const LOGUED_USER = "LOGUED_USER";
